(()=>{
const content=document.getElementById('content');
const LEVELS={
1:{m:['četiri srčane šupljine, glavni zalisci i smjer toka krvi','mali i veliki krvni optok','što su puls i srčana frekvencija','osnovna uloga provodnog sustava'],o:['povezati SA/AV čvor s osnovnim EKG valovima','objasniti zašto tahikardija ili bradikardija mogu utjecati na perfuziju'],n:['udarni i minutni volumen kao stručna nadogradnja']},
2:{m:['prvo promatrati bolesnika, zatim brojke na monitoru','procijeniti bol, disanje, svijest, perfuziju, edeme i izlučevine','prepoznati osnovnu opremu JIKS-a/JIL-a','prepoznati crvene zastavice i pravodobno aktivirati tim'],o:['pratiti trend vitalnih znakova','objektivno dokumentirati promjenu','primijeniti SBAR komunikaciju'],n:['razlika JIKS/JIL i osnovna logika kontinuiranog monitoringa']},
3:{m:['svrha 12-kanalnog EKG-a','pravilan položaj V1–V6','osnovno značenje P, QRS i T','prepoznati moguć artefakt i uvijek provjeriti bolesnika'],o:['objasniti zašto 10 elektroda daje 12 odvoda','povezati EKG s pulsom, tlakom, sviješću i simptomima'],n:['detaljnija interpretacija ishemije i aritmija pripada višoj razini']},
4:{m:['pravila sigurne primjene lijekova','što provjeriti prije i pratiti nakon ordinirane terapije','rizik krvarenja uz antitrombocitnu/antikoagulantnu terapiju','kisik se primjenjuje prema indikaciji i protokolu'],o:['povezati nitrate, beta-blokatore i diuretike s parametrima praćenja','prepoznati hipotenziju, bradikardiju, krvarenje i poremećaje elektrolita'],n:['RAAS/ARNI, MRA i SGLT2 – stručna nadogradnja bez učenja doziranja']},
5:{m:['tipična i atipična klinička slika ACS-a/AIM-a','OPQRST procjena boli','12-kanalni EKG što prije i uloga hs-troponina','osnovna svrha PCI-ja','prioritetni sestrinski postupci i komplikacije'],o:['razlikovati STEMI, NSTEMI i nestabilnu anginu na srednjoškolskoj razini','povezati rupturu plaka, tromb, ishemiju i nekrozu'],n:['ubrzani biomarker algoritmi i detaljna reperfuzijska strategija']},
6:{m:['lijevo i desno srčano popuštanje','dispneja, ortopneja, edemi i kongestija','plućni edem kao hitno stanje','položaj, monitoring, diureza i sestrinski prioriteti'],o:['razlikovati kongestiju i hipoperfuziju','objasniti vrijednost tjelesne mase, diureze i edema kao trenda'],n:['ESC 2026 HFrEF/HFpEF i stadiji A–D – stručna nadogradnja, ne važnija od kliničke slike i njege']},
7:{m:['pravilna tehnika mjerenja krvnog tlaka','osnovna klasifikacija povišenog tlaka i hipertenzije','hipertenzivna emergencija znači akutno oštećenje ciljnih organa','znakovi DVT-a i plućne embolije'],o:['kućno/24-satno mjerenje kada je indicirano','razlikovati vensku insuficijenciju, DVT i PE'],n:['detaljna procjena ukupnog KV rizika i antikoagulantna strategija']},
8:{m:['procjena → problem → cilj → intervencije → evaluacija','planirati edukaciju i provjeru razumijevanja','crvene zastavice za hitnu pomoć','plan otpusta i dokumentacija'],o:['primijeniti metodu povratnog objašnjavanja','izraditi jednostavan plan njege za scenarij'],n:['individualizacija edukacije prema zdravstvenoj pismenosti i komorbiditetima']},
9:{m:['povezati mehanizam sa simptomom i sestrinskim opažanjem','objasniti put krvi, osnovni EKG, ACS, plućni edem, hipoperfuziju i DVT→PE','nakon simulacije objasniti što bi sestra prvo procijenila'],o:['usporediti dva mehanizma u istom kliničkom scenariju'],n:['integrirati više sustava i prioriteta u složenom scenariju']},
10:{m:['odgovor: definicija → uzrok/mehanizam → klinička slika → dijagnostika/liječenje → zdravstvena njega → edukacija/crvene zastavice','odgovarati vlastitim riječima','u scenariju prvo odrediti hitnost i prioritete'],o:['povezati više lekcija i obrazložiti zašto je nešto prioritet'],n:['samostalno procijeniti kvalitetu odgovora i ciljano ponavljati slabija područja']}
};
const CHECKS={
1:[['Koja klijetka izbacuje krv u aortu?','Lijeva klijetka.'],['Zašto plućna arterija nosi deoksigeniranu krv?','Arterija znači da krv odvodi od srca; plućna arterija vodi krv iz desne klijetke prema plućima.'],['Što procjenjujemo na pulsu osim frekvencije?','Ritam, jačinu/punjenost i, kada je važno, simetriju.'],['Koji zalistak je između lijeve pretklijetke i klijetke?','Mitralni zalistak.'],['Što znači tahikardija?','Srčana frekvencija iznad uobičajenog raspona; u odrasle osobe u mirovanju često >100/min, uz obveznu kliničku procjenu.']],
2:[['Što prvo radiš kada monitor zazvoni alarm?','Najprije procijeni bolesnika, zatim provjeri signal, elektrode/senzore, kabele i uzrok alarma.'],['Koji znakovi upućuju na hipoperfuziju?','Hladna periferija, slab puls, hipotenzija, oligourija, konfuzija i produženo kapilarno punjenje.'],['Čemu služi štrcaljkasta pumpa?','Preciznoj kontinuiranoj primjeni malih volumena lijekova/otopina.'],['Što mora sadržavati dokumentacija pogoršanja?','Vrijeme, objektivan nalaz, mjerljive vrijednosti, provedene postupke, komunikaciju s timom i odgovor bolesnika.'],['Što znači SBAR?','Strukturirana komunikacija: Situacija, Pozadina, Procjena, Zahtjev/preporuka.']],
3:[['Koliko elektroda koristimo za standardni 12-kanalni EKG?','10 elektroda: 4 ekstremitetne i 6 prekordijalnih.'],['Gdje je V1?','4. međurebreni prostor desno od sternuma.'],['Što prvenstveno predstavlja QRS?','Depolarizaciju klijetki.'],['Što može uzrokovati valovitu baznu liniju?','Pokret, tremor, loš kontakt kože/elektrode ili električni artefakt.'],['Zašto EKG ne čekamo do nalaza troponina kod sumnje na ACS?','Jer je EKG vremenski kritičan za rano prepoznavanje stanja koja zahtijevaju hitnu reperfuziju.']],
4:[['Što posebno provjeravamo prije beta-blokatora?','Puls, krvni tlak, ritam i kliničku stabilnost prema ordinaciji/protokolu.'],['Koji je glavni sigurnosni rizik antikoagulantne terapije?','Krvarenje.'],['Što pratimo uz diuretik?','Diurezu, tjelesnu masu/edeme, tlak, elektrolite i bubrežnu funkciju prema nalogu.'],['Daje li se kisik rutinski svakom bolesniku s ACS-om?','Ne; primjenjuje se kod hipoksemije, respiratornog distresa ili druge jasne indikacije prema protokolu.'],['Tko ordinira lijek i dozu?','Liječnik/ovlašteni propisivač; medicinska sestra/tehničar sigurno provodi ordinirano i prati učinak.']],
5:[['Koji postupak ne treba odgađati kod sumnje na ACS?','12-kanalni EKG i početnu kliničku procjenu.'],['Što nam govori hs-troponin?','Pomaže dokazati ozljedu miokarda i tumači se uz simptome, EKG i dinamičku promjenu vrijednosti.'],['Čemu služi OPQRST?','Strukturiranoj procjeni boli: početak, provociranje/olakšavanje, kvaliteta, širenje, intenzitet i vrijeme.'],['Koja je osnovna svrha primarne PCI kod STEMI-ja?','Što prije ponovno uspostaviti protok kroz zatvorenu koronarnu arteriju kada je pravodobno dostupna.'],['Navedi tri opasne komplikacije AIM-a.','Maligne aritmije/srčani zastoj, srčano popuštanje/plućni edem i kardiogeni šok; moguće su i mehaničke komplikacije.']],
6:[['Što je ortopneja?','Dispneja pri ležanju koja se olakšava uspravljanjem/sjedećim položajem.'],['Što znači kongestija?','Zastoj krvi i nakupljanje tekućine zbog povišenih punidbenih tlakova.'],['Koji su znakovi plućnog edema?','Nagla teška dispneja, tahipneja, hipoksemija/cijanoza, hropci, nemir, znojenje i mogući pjenasti iskašljaj.'],['Zašto pratimo dnevnu tjelesnu masu?','Brz porast može biti rani znak zadržavanja tekućine.'],['Što je za 3. razred važnije: ESC fenotip EF-a ili prepoznavanje dekompenzacije?','Prepoznavanje simptoma, znakova, crvenih zastavica i pravilna zdravstvena njega; ESC klasifikacija je stručna nadogradnja.']],
7:[['Kako položaj ruke utječe na mjerenje tlaka?','Ruka treba biti poduprta približno u razini srca; pogrešan položaj može iskriviti rezultat.'],['Što može učiniti premala manžeta?','Dati lažno višu vrijednost.'],['Što hipertenzivnu emergenciju čini hitnom?','Akutno oštećenje ciljnih organa, a ne samo brojka tlaka.'],['Smije li se masirati noga kod sumnje na DVT?','Ne; potrebna je liječnička procjena i postupanje prema protokolu.'],['Koji simptomi mogu upućivati na PE?','Iznenadna dispneja, pleuritična bol, tahikardija, hipoksemija, hemoptiza ili sinkopa.']],
8:[['Koji je prvi korak plana zdravstvene njege?','Sestrinska procjena.'],['Što je metoda povratnog objašnjavanja?','Bolesnik svojim riječima ili demonstracijom pokaže što je razumio.'],['Kakav treba biti cilj?','Povezan s problemom, realan i procjenjiv/evaluabilan.'],['Zašto je evaluacija obvezna?','Da utvrdimo jesu li intervencije djelovale i treba li plan mijenjati.'],['Koja je važna edukacija nakon AIM-a?','Adherencija terapiji, kontrola rizičnih čimbenika, rehabilitacija i prepoznavanje alarmantnih simptoma.']],
9:[['Kako slaba lijeva klijetka dovodi do dispneje?','Povećava tlak u plućnim venama/kapilarama, nastaju kongestija i edem te se pogoršava izmjena plinova.'],['Kako DVT može dovesti do PE?','Dio tromba se odvoji, putuje venskim sustavom kroz desno srce i začepljuje plućnu arteriju.'],['Zašto oligourija može biti znak hipoperfuzije?','Bubrezi dobivaju manje krvi kada je minutni volumen nedovoljan.'],['Što radiš ako zapis na monitoru izgleda kao aritmija, a bolesnik je stabilan?','Procijeni bolesnika i puls te provjeri elektrode, senzore, kabele i artefakt; po potrebi snimi odgovarajući EKG.'],['Kako najbolje koristiti simulaciju?','Nakon svakog koraka vlastitim riječima objasniti mehanizam, simptome i sestrinski prioritet.']],
10:[['Kako strukturirati odgovor na usmenom?','Definicija → uzrok/mehanizam → klinička slika → dijagnostika/liječenje → zdravstvena njega → edukacija/crvene zastavice.'],['Što je prvo u kliničkom scenariju?','Odrediti hitnost, sigurnost bolesnika i prioritete procjene.'],['Što ako ne znaš dozu lijeka?','Ne izmišljati; navesti da se lijek primjenjuje po ordinaciji i opisati što sestra provjerava i prati.'],['Kada gledati model odgovora?','Nakon vlastitog pokušaja, kao provjeru strukture i sadržaja.'],['Kako znaš da si spreman?','Možeš objasniti vlastitim riječima, povezati gradivo i primijeniti znanje na scenarij.']]
};
function ul(a){return '<ul>'+a.map(x=>'<li>'+x+'</li>').join('')+'</ul>'}
function injectLevels(lesson,n){if(lesson.querySelector('.zn3-levels')||!LEVELS[n])return;const d=LEVELS[n],box=document.createElement('section');box.className='zn3-levels';box.innerHTML=`<div class="zn3-level must"><h4>🎯 MORAŠ ZNATI</h4><p class="level-note">Temelj za svakog učenika 3. razreda.</p>${ul(d.m)}</div><div class="zn3-level excellent"><h4>⭐ ZA VRLO DOBAR / ODLIČAN</h4><p class="level-note">Povezivanje i dublje razumijevanje.</p>${ul(d.o)}</div><div class="zn3-level advanced"><h4>🔬 STRUČNA NADOGRADNJA</h4><p class="level-note">Suvremena širina; nije iste težine kao temeljno gradivo.</p>${ul(d.n)}</div>`;(lesson.querySelector('.lesson-map')||lesson.querySelector('.lesson-header'))?.insertAdjacentElement('afterend',box)}
function injectCheck(lesson,n){if(lesson.querySelector('.zn3-quiz')||!CHECKS[n])return;const box=document.createElement('section');box.className='zn3-quiz';box.innerHTML=`<div class="zn3-quiz-head"><div><span class="skill-badge">SAMOPROVJERA</span><h3>5 brzih pitanja – provjeri razumijevanje</h3></div><div class="zn3-quiz-score">Lekcija ${String(n).padStart(2,'0')}</div></div>${CHECKS[n].map((x,i)=>`<details class="zn3-q"><summary><strong>${i+1}. ${x[0]}</strong></summary><div class="zn3-feedback"><strong>Model odgovora:</strong> ${x[1]}</div></details>`).join('')}`;const nav=lesson.querySelector('.nav-bottom');if(nav)lesson.insertBefore(box,nav);else lesson.appendChild(box)}
function split7(lesson){if(lesson.querySelector('.submodule-banner'))return;const ss=[...lesson.querySelectorAll(':scope > .section')],h=ss.find(s=>/krvni tlak|hipertenz/i.test(s.querySelector('h3')?.textContent||'')),v=ss.find(s=>/vensk|DVT|trombo/i.test(s.querySelector('h3')?.textContent||''));if(h){const b=document.createElement('div');b.className='submodule-banner';b.innerHTML='<h3>07A Krvni tlak i arterijska hipertenzija</h3><p>Mjerenje → klasifikacija → oštećenje ciljnih organa → liječenje → zdravstvena njega → hitna stanja.</p>';h.before(b)}if(v){const b=document.createElement('div');b.className='submodule-banner';b.innerHTML='<h3>07B Venske bolesti, DVT i plućna embolija</h3><p>Venska insuficijencija → DVT → embolus → plućna embolija → crvene zastavice.</p>';v.before(b)}}
function terminology(lesson){const pairs=[['bedside monitor','monitor uz bolesnički krevet'],['Teach-back','metoda povratnog objašnjavanja'],['teach-back','metoda povratnog objašnjavanja']];const w=document.createTreeWalker(lesson,NodeFilter.SHOW_TEXT),a=[];while(w.nextNode())a.push(w.currentNode);a.forEach(n=>{let s=n.nodeValue;pairs.forEach(([x,y])=>s=s.split(x).join(y));n.nodeValue=s})}
function run(){const lesson=content?.querySelector('.lesson.active');if(!lesson)return;const n=Number((lesson.id||'').replace('lesson-',''));if(!n)return;injectLevels(lesson,n);injectCheck(lesson,n);if(n===7)split7(lesson);terminology(lesson)}let t;if(content)new MutationObserver(()=>{clearTimeout(t);t=setTimeout(run,160)}).observe(content,{childList:true,subtree:true});run();
})();