(()=>{
const content=document.getElementById('content');
const LEVELS={
1:{m:['osnovna građa srca i smjer toka krvi','mali i veliki krvni optok','koronarna cirkulacija i veza s infarktom','glavni promjenjivi kardiovaskularni čimbenici rizika'],o:['objasniti vezu srčanog ciklusa, pulsa i perfuzije','razlikovati primarnu, sekundarnu i tercijarnu prevenciju'],n:['udarni i minutni volumen kao dodatno fiziološko razumijevanje']},
2:{m:['uzeti osnovnu kardiološku anamnezu','procijeniti bol OPQRST metodom','promatrati svijest, kožu, disanje, puls, tlak, SpO₂, edeme i diurezu','razlikovati monitor bolesnika od respiratora i prepoznati osnovnu JIKS/JIL opremu'],o:['pratiti trend vitalnih znakova i objektivno dokumentirati promjene','prenijeti pogoršanje strukturirano SBAR metodom'],n:['šira ABCDE procjena i organizacija intenzivne skrbi']},
3:{m:['svrha 12-kanalnog EKG-a i pravilno V1–V6','razlika između kontinuiranog monitoringa i dijagnostičkog EKG-a','uloga hs-troponina','osnovna uloga RTG-a, ehokardiografije i koronarografije'],o:['povezati simptom s odgovarajućom pretragom','opisati sestrinski nadzor nakon koronarografije/PCI-ja'],n:['detaljna interpretacija EKG-a i invazivna dijagnostika pripadaju višoj razini']},
4:{m:['pravila sigurne primjene lijekova','što pratiti uz antitrombotsku terapiju, nitrate, beta-blokatore i diuretike','kisik kao lijek prema indikaciji','ne izmišljati doze niti samostalno mijenjati ordinaciju'],o:['povezati tlak, puls, kalij, bubrežnu funkciju i diurezu s terapijskom sigurnošću','objasniti osnovnu svrhu statina i suvremenih lijekova za HF'],n:['RAAS/ARNI, MRA i SGLT2 kao stručna nadogradnja bez učenja doziranja']},
5:{m:['nastanak ACS-a: plak → ruptura → tromb → ishemija/nekroza','tipični i atipični simptomi AIM-a','EKG što prije i uloga hs-troponina','osnovna svrha PCI-ja i prioriteti zdravstvene njege','rane komplikacije i edukacija nakon infarkta'],o:['konceptualno razlikovati STEMI, NSTEMI i nestabilnu anginu','objasniti zašto kisik nije rutinski za svakoga i zašto se bolesnik prati zbog krvarenja/aritmija'],n:['podtipovi infarkta i detaljni reperfuzijski algoritmi']},
6:{m:['prepoznati dekompenzaciju: dispneja, ortopneja, edemi i porast težine','razlikovati kongestiju i hipoperfuziju','prepoznati plućni edem kao hitno stanje','pratiti diurezu, težinu, edeme, SpO₂, tlak i odgovor na diuretik','znati prioritete prvih minuta kod plućnog edema'],o:['povezati BNP/NT-proBNP, RTG i UZV srca s procjenom HF-a','objasniti lijevo i desno srčano popuštanje'],n:['ESC 2026 HFrEF/HFpEF i stadiji A–D kao stručna nadogradnja']},
7:{m:['pravilna tehnika mjerenja krvnog tlaka','ESC 2024: povišen tlak i prag hipertenzije','glavni čimbenici rizika i oštećenja ciljnih organa','hipertenzivna emergencija znači akutno oštećenje organa, ne samo visoku brojku','edukacija za kućno mjerenje i redovitu terapiju'],o:['razlikovati primarnu i sekundarnu hipertenziju','objasniti bijelu kutu, maskiranu hipertenziju i ABPM'],n:['ciljni tlak i detaljna procjena ukupnog kardiovaskularnog rizika']},
8:{m:['sestrinski proces: procjena → problem → cilj → intervencije → evaluacija','prioritetni plan njege kod AIM-a, dekompenzacije i hipertenzije','sigurnost lijekova i samokontrola','crvene zastavice i kontrolna lista za otpust'],o:['primijeniti metodu povratnog objašnjavanja','izraditi jednostavan individualizirani plan njege'],n:['prilagoditi edukaciju zdravstvenoj pismenosti, komorbiditetima i socijalnim okolnostima']},
9:{m:['povezati anamnezu, simptome, mjerenja i sestrinski prioritet','objasniti mehanizam AIM-a, plućnog edema i hipertenzivnog pogoršanja','razlikovati monitor od respiratora','nakon simulacije objasniti što prvo procjenjuješ'],o:['riješiti kratki klinički scenarij i obrazložiti prioritet'],n:['integrirati više problema istodobno u složenom scenariju']},
10:{m:['strukturirati usmeni odgovor prema kliničkom putu','odgovarati vlastitim riječima','u scenariju prvo odrediti hitnost i sigurnost','znati glavne crvene zastavice'],o:['povezati više lekcija i obrazložiti zašto je nešto prioritet'],n:['samostalno procijeniti kvalitetu odgovora i ciljano ponoviti slabije područje']}
};
const CHECKS={
1:[['Koja klijetka izbacuje krv u aortu?','Lijeva klijetka.'],['Koja je osnovna svrha koronarne cirkulacije?','Opskrbiti srčani mišić kisikom i hranjivim tvarima.'],['Navedi četiri promjenjiva kardiovaskularna čimbenika rizika.','Primjerice pušenje, hipertenzija, šećerna bolest, dislipidemija, pretilost, tjelesna neaktivnost i nezdrava prehrana.'],['Zašto plućna arterija nosi krv siromašniju kisikom?','Arterija se definira smjerom od srca; plućna arterija vodi krv iz desne klijetke prema plućima.'],['Što je sekundarna prevencija?','Rano otkrivanje/liječenje bolesti i sprječavanje ponovnog događaja ili napredovanja.']],
2:[['Koje četiri skupine podataka obuhvaća osnovna anamneza?','Aktualne tegobe, ranije bolesti/događaji, terapija i alergije te navike/obiteljska anamneza.'],['Što znači OPQRST?','Strukturirana procjena početka, provociranja/olakšanja, kvalitete, širenja, intenziteta i tijeka boli.'],['Što prvo radiš kada monitor alarmira?','Prvo procijeni bolesnika, zatim provjeri signal, elektrode/senzore i tehnički uzrok alarma.'],['Koja je razlika monitora i respiratora?','Monitor mjeri/prikazuje fiziološke parametre; respirator aktivno pruža mehaničku ventilacijsku potporu.'],['Što znači SBAR?','Situacija, Pozadina, Procjena, Zahtjev/preporuka.']],
3:[['Koliko elektroda koristimo za standardni 12-kanalni EKG?','10 elektroda: četiri ekstremitetne i šest prekordijalnih.'],['Gdje se postavlja V1?','U 4. međurebreni prostor desno uz sternum.'],['Čemu služi hs-troponin?','Za dokaz i praćenje ozljede miokarda; tumači se uz simptome, EKG i dinamiku vrijednosti.'],['Koja je razlika između monitoringa i 12-kanalnog EKG-a?','Monitoring kontinuirano prati odabrane parametre; 12-kanalni EKG daje standardizirani dijagnostički zapis iz 12 odvoda.'],['Što pratimo nakon koronarografije/PCI-ja?','Vitalne znakove, mjesto punkcije, krvarenje/hematom, distalnu perfuziju, bol i opće stanje prema protokolu.']],
4:[['Tko određuje lijek i dozu?','Liječnik/ovlašteni propisivač; sestra/tehničar sigurno provodi ordinirano i prati učinak.'],['Koji je glavni sigurnosni rizik antikoagulantne terapije?','Krvarenje.'],['Što posebno pratimo uz diuretik?','Diurezu, težinu/edeme, tlak, elektrolite, bubrežnu funkciju i klinički odgovor.'],['Daje li se kisik rutinski svakome s AIM-om?','Ne. Daje se kod hipoksemije, respiratornog distresa ili druge jasne indikacije prema protokolu.'],['Zašto su kalij i kreatinin važni uz dio kardiološke terapije?','Poremećaji kalija povećavaju rizik aritmija, a bubrežna funkcija utječe na sigurnost više lijekova.']],
5:[['Kako aterosklerotski plak može dovesti do infarkta?','Ruptura/erozija plaka može pokrenuti stvaranje tromba koji smanji ili prekine koronarni protok te izazove ishemiju i nekrozu.'],['Koji se postupak ne smije nepotrebno odgađati kod sumnje na ACS?','12-kanalni EKG i početna klinička procjena.'],['Zašto hs-troponin ne zamjenjuje EKG?','Jer ACS dijagnostika kombinira kliničku sliku, EKG i biomarkere, a hitna reperfuzija se ne smije odgađati čekanjem biomarkera.'],['Koja je osnovna svrha primarne PCI kod STEMI-ja?','Što prije ponovno uspostaviti protok kroz zatvorenu koronarnu arteriju.'],['Navedi tri opasne komplikacije AIM-a.','Maligne aritmije/srčani zastoj, akutno srčano popuštanje/plućni edem i kardiogeni šok; moguće su i mehaničke komplikacije.']],
6:[['Što je ortopneja?','Dispneja u ležećem položaju koja se olakšava uspravljanjem/sjedećim položajem.'],['Što znači kongestija?','Zastoj krvi i nakupljanje tekućine zbog povišenih punidbenih tlakova.'],['Koji su važni znakovi plućnog edema?','Nagla teška dispneja, ortopneja, tahipneja, hropci, hipoksemija/cijanoza, nemir, znojenje i mogući pjenasti iskašljaj.'],['Zašto pratimo dnevnu tjelesnu masu?','Brz porast može biti rani znak zadržavanja tekućine.'],['Što je za treći razred važnije od memoriranja EF klasifikacije?','Prepoznati dekompenzaciju, crvene zastavice i pravilno provesti zdravstvenu njegu.']],
7:[['Kako se priprema bolesnik za pravilno mjerenje tlaka?','Odmor, leđa i stopala poduprti, noge neprekrižene, ruka u razini srca, odgovarajuća manžeta i bez razgovora tijekom mjerenja.'],['Kako ESC 2024 definira uredsku hipertenziju?','Sistolički tlak ≥140 i/ili dijastolički ≥90 mmHg.'],['Zašto se hipertenzija naziva tihim ubojicom?','Jer često nema specifične simptome, a može godinama oštećivati ciljne organe.'],['Što čini hipertenzivnu emergenciju hitnom?','Akutno oštećenje ciljnih organa uz izrazito povišen tlak, a ne sama brojka.'],['Što je maskirana hipertenzija?','Uredski tlak nije povišen, ali su vrijednosti kod kuće/ABPM povišene.']],
8:[['Koji je prvi korak sestrinskog procesa?','Procjena bolesnika.'],['Što je metoda povratnog objašnjavanja?','Bolesnik svojim riječima ili demonstracijom pokaže što je razumio.'],['Što mora sadržavati dobar cilj njege?','Mora biti povezan s problemom, realan i moguće ga je evaluirati.'],['Navedi četiri elementa kontrolne liste za otpust.','Terapija, samokontrola, plan kontrola, aktivnost/rehabilitacija, prehrana/navike, crvene zastavice i provjera razumijevanja.'],['Zašto je evaluacija važna?','Pokazuje jesu li intervencije djelovale i treba li plan promijeniti.']],
9:[['Koja tri pitanja trebaš sebi postaviti nakon svake simulacije?','Što se događa, što očekujem kod bolesnika i što prvo procjenjujem/radim.'],['Kako razlikuješ monitor od respiratora?','Monitor prati/mjeri parametre; respirator pruža ventilacijsku potporu.'],['Što je prioritet kod nove boli u prsima i hladnog znoja?','ABC, vitalni znakovi, hitna komunikacija i 12-kanalni EKG što prije uz daljnje postupanje prema protokolu.'],['Što povezuje ortopneju, edeme i porast tjelesne mase?','Moguće pogoršanje kongestije kod srčanog popuštanja.'],['Zašto visoka vrijednost tlaka sama ne definira emergenciju?','Emergencija zahtijeva znakove akutnog oštećenja ciljnih organa.']],
10:[['Kako strukturirati odgovor na usmenom?','Definicija → rizici/uzrok → anamneza/klinička slika → dijagnostika → liječenje → zdravstvena njega → edukacija.'],['Što je prvo u kliničkom scenariju?','Procijeniti hitnost i sigurnost bolesnika.'],['Što ako ne znaš dozu lijeka?','Ne izmišljati; navesti da se primjenjuje po ordinaciji i opisati sigurnosna opažanja.'],['Kada gledati model odgovora?','Nakon vlastitog pokušaja, radi provjere strukture i sadržaja.'],['Kako znaš da si spreman?','Možeš objasniti vlastitim riječima, povezati gradivo i primijeniti ga na novi scenarij.']]
};
function list(a){return '<ul>'+a.map(x=>'<li>'+x+'</li>').join('')+'</ul>'}
function injectLevels(lesson,n){if(lesson.querySelector('.zn3-levels')||!LEVELS[n])return;const d=LEVELS[n],box=document.createElement('section');box.className='zn3-levels section';box.innerHTML=`<h3>Što trebaš znati iz ove lekcije?</h3><div class="level-grid"><article class="level-card must"><span>🎯 MORAŠ ZNATI</span>${list(d.m)}</article><article class="level-card excellent"><span>⭐ ZA VRLO DOBAR / ODLIČAN</span>${list(d.o)}</article><article class="level-card advanced"><span>🔬 STRUČNA NADOGRADNJA</span>${list(d.n)}</article></div>`;const h=lesson.querySelector('.lesson-header');h?.insertAdjacentElement('afterend',box)}
function injectChecks(lesson,n){if(lesson.querySelector('.zn3-checks')||!CHECKS[n])return;const s=document.createElement('section');s.className='zn3-checks section';s.innerHTML='<h3>Brza samoprovjera – 5 pitanja</h3><p>Najprije odgovori naglas. Tek zatim otvori model odgovora.</p>'+CHECKS[n].map((q,i)=>`<details><summary>${i+1}. ${q[0]}</summary><p>${q[1]}</p></details>`).join('');const nav=lesson.querySelector('.nav-bottom');if(nav)nav.insertAdjacentElement('beforebegin',s);else lesson.appendChild(s)}
function apply(){const lesson=content?.querySelector('.lesson.active');if(!lesson)return;const id=Number((lesson.id||'').replace('lesson-',''));if(!id)return;injectLevels(lesson,id);injectChecks(lesson,id)}
let t;function schedule(){clearTimeout(t);t=setTimeout(apply,120)}
if(content)new MutationObserver(schedule).observe(content,{childList:true,subtree:true});schedule();
})();